config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :lists, only: %i[new create show index update edit] do
    resources :bookmarks, only: %i[new create]
    resources :reviews, only: %i[create]
  end

  resources :movies, only: [:index]
  resources :bookmarks, only: [:destroy]
  root to: 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, presence: true, uniqueness: { scope: :list }
  validates :list, presence: true
  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :restrict_with_error
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list, dependent: :destroy

  validates :comment, presence: true
  validates :rating, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to @list
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy

    redirect_to @list
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, only: %i[show edit update]
  def index
    @lists = List.all
  end

  def show
    @review = Review.new
    @review.list = @list
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @list.update(list_params)
      redirect_to @list
    else
      render :edit
    end
  end

  private

  def find_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @list = List.find(params[:list_id])
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save
      redirect_to @list
    else
      render 'lists/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>New bookmark to <strong class="colorfull"><%= @list.name  %></strong></h1>

  <%= simple_form_for [@list, @bookmark]  do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie, include_blank: false %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
  <hr>
  <%= link_to 'Back', list_path(@list), class:'btn' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'typed', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-dark bg-dark navbar-lewagon sticky-top">
      <div class="container-fluid">
        <%= link_to "#", class: "navbar-brand" do %>
          <%= image_tag "https://icons.veryicon.com/png/o/movie--tv/color-01/movie-ticket-3.png", alt: 'icon' %>
        <% end %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <li class="nav-item active">
              <%= link_to "Lists", lists_path , class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Movies", movies_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list)  do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/lists/edit.html.erb
<div class="container">
  <h1>Update <%= @list.name %> List Cover image</h1>
  <%= simple_form_for(@list)  do |f| %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
  <hr>
  <%= link_to 'Back', lists_path, class:'btn' %>
</div>

app/views/lists/index.html.erb
<div class="banner" style= "background-image: linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1583024673717-4ede2b33fd71?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1010&q=80);">
  <h1 class="text-center">Save any kind of <strong class="colorfull">movie</strong></h1>

    <p class="text-center">The
    <%= link_to movies_path, class:'colorfull-a' do %>
      <span>best collection</span>
    <% end %>
    of movies</p>
</div>

<div class="container my-5">
  <div class="cards">
    <% @lists.each do |list| %>
      <% if list.photo.attached? %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.8)), url('<%= cl_image_path list.photo.key %>')">
      <% else %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">
      <% end %>
        <%= link_to list.name, list_path(list), class:'btn btn-lg' %>
      </div>
    <% end %>
  </div>

  <%= link_to 'Create a List!', new_list_path, class: 'btn btn-success my-3' %>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>New list</h1>
  <%= render "form", list: @list %>
  <hr>
  <%= link_to 'Back', lists_path, class:'btn' %>
</div>

app/views/lists/show.html.erb
<% if @list.photo.attached? %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.photo.key %>');">
<% else %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4));">
<% end %>
    <div class="container">
      <h1><%= @list.name %></h1>
    </div>
  </div>


<div class="container my-4">
  <%= link_to 'Add bookmark', new_list_bookmark_path(@list), class: 'btn btn-success' %> |
  <%= link_to 'Back', lists_path, class: 'btn' %> |
  <%= link_to 'Upload List cover', edit_list_path(@list), class: 'btn btn-success' %>
  <hr>
  <h2>Movies:</h2>
  <div class="cards">
      <% @list.bookmarks.each do |bookmark| %>
        <div class="card">
          <%= image_tag bookmark.movie.poster_url, alt:'poster', class: 'card-img-top'  %>
          <div class="card-body">
            <h2 class="card-title"><%= bookmark.movie.title  %></h2> <span><%= "⭐  #{bookmark.movie.rating.round(1)}" %></span>
            <p class="card-text"><%= bookmark.movie.overview  %></p>
            <p><%= link_to 'Delete',
                      bookmark_path(bookmark),
                      method: :delete,
                      data: { confirm: "Are you sure?" },
                      class: 'btn btn-danger'  %>
            </p>
          </div>
        </div>
      <% end %>
  </div>
  <hr>
</div>
<div class="container d-flex justify-content-around">
  <div class="reviews-container">
    <h3 class="colorfull-a">Reviews</h3>
      <hr>
      <% @list.reviews.each do |review| %>
        <p><%= '⭐'* review.rating %></p>
        <p> <%= review.comment %></p>
        <hr>
      <% end %>
  </div>
  <div class="reviews-form m-4">
    <%= simple_form_for [@list,@review]  do |f| %>
      <%= f.input :comment %>
      <%= f.input :rating, collection: 1..5, class: 'br-widget'  %>
      <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/movies/index.html.erb
<div class="container">
  <h1 class="colorfull text-center">Movies List</h1>
  <div class="cards my-5">
    <% @movies.each do |movie| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= movie.poster_url %>)">
        <p class="text-center"><%= movie.title  %></p>
      </div>
    <% end %>
  </div>

</div>